### PR TITLE
Release 0.12.4

### PR DESCRIPTION
**Pull request by nsheff**
Needed in support of caravel release.

~~**wait for [these issues]( https://github.com/pepkit/looper/milestone/6) to be resolved**~~

Needs:
- [x] changelog
- [x] version

### CODE REVIEW

**Comment by nsheff** [comment]
@vreuter is this ready to go from your pespective?

**Comment by nsheff** [comment]
will this depend on a peppy release or are we good to go?

**Comment by michalstolarczyk** [comment]
In Travis the currently released `peppy` is being installed and all checks do pass. I also confirm locally that unit tests pass.
Looking at the `dev`/`master` diff in `peppy` the commits are related to the new characteristic of the sample table -- uniqueness of the entries in `sample_name` column. So I think it's unlikely that it is required for this version of `looper`

**Comment by vreuter** [comment]
> @vreuter is this ready to go from your perspective?

Yes

**Comment by vreuter** [comment]
> will this depend on a peppy release or are we good to go?

I don’t have access to my computer right now, but I think the changes I added here would only need the released peppy

**Pull request merged**
