### PR TITLE
0.12.3

### PR DESCRIPTION
**Pull request by vreuter**
- Fixes bug in sample YAML filename generation reported by @afrendeiro 
- Uses from `peppy` important constants regarding writing a `Sample` to disk.
- In submission conductor, uses the sample subtype provided to the constructor rather than ignoring it, as was previously the case; instead, we were always getting base `Sample` instances since we were never passing a subtype in an `add_sample` call.

### CODE REVIEW

**Comment by vreuter** [comment]
@nsheff the most interesting changes are in `conductor.py`

**Comment by nsheff** [comment]
I haven't had time to test this in a real use case. can you confirm that it's not breaking anything in a typical use? as you brought up recently with integration tests, we often have issues with releases that are breaking things that we're not testing, so I just want to make sure we at least try a few things, since unit tests can't really cover those scenarios. maybe this would be a good time to throw together some very basic 'integration tests' as you proposed.

**Comment by nsheff** [comment]
microtest would be a good example -- just confirm that you can run the microtest project successfully. that was the original point of it.

**Comment by vreuter** [comment]
> microtest would be a good example -- just confirm that you can run the microtest project successfully. that was the original point of it.

Well, not everything is "submitted" upon dry run, but there's no difference in that regard compared to 0.12.2 using the following test procedure; it looks like the version number accounts for the only difference.
1. Install desired version in virtual env
2. Run on `master` of `databio/microtest`
3. Store the terminal output in text file
4. Take the `diff`

This results:
```
@ ~ () $ diff looper_v0.12.2_microtest_output.txt looper_v0.12.3_microtest_output.txt 
1,2c1,2
< @ ~ () $ looper run -d ~/code/microtest/config/microtest_config.yaml 
< Command: run (Looper version: 0.12.2)
---
> @ ~/code/looper (dev) $ looper run -d ~/code/microtest/config/microtest_config.yaml 
> Command: run (Looper version: 0.12.3)
```

Overall, my end result for both versions is like:
```
Looper finished
Samples valid for job generation: 8 of 20
Successful samples: 4 of 20
Commands submitted: 4 of 10
Jobs submitted: 4
Dry run. No jobs were actually submitted.

4 unique reasons for submission failure: No pipeline for protocol, Missing attribute, Required attribute missing for pipeline arguments string, Missing file(s)

Summary of failures:
No pipeline for protocol: Amplicon_human, ChIP-seq_human_H3K27ac_PE, Quant-seq_human, Drop-seq_mouse, ChIPmentation_human_H3K27ac_SE, ChIPmentation_human_CTCF_SE, Drop-seq_human, ChIPmentation_human_CTCF_PE, ChIPmentation_human_H3K27ac_PE, ChIP-seq_human_CTCF_SE, ChIP-seq_human_CTCF_PE, ChIP-seq_human_H3K27ac_SE
Missing attribute: ATAC-seq_human_PE, ATAC-seq_human_SE
Required attribute missing for pipeline arguments string: ATAC-seq_human_PE, ATAC-seq_human_SE
Missing file(s): SMART-seq_human_truseq_SE, SMART-seq_human_SE
```

**Comment by nsheff** [comment]
great -- looks good. I wonder if we should containerize this kind of test and make it simple to run...

**Pull request merged**
