### PR TITLE
Simpler CLI bubbling

### PR DESCRIPTION
**Pull request by vreuter**
Flattened `CliOpt` type from https://github.com/pepkit/looper/pull/87.

### CODE REVIEW

**Comment by nsheff** [comment]
The flattened object does make more sense to me. I think I understand what you're doing but I'm not sure. Can you explain the problem you're trying to solve?

Are you re-implementing something that argumentparser does, like the mutual exclusive option group? Is it so that caravel can get the needed information out of it?

**Comment by vreuter** [comment]
Yeah, one is definite and immediate; the other is more hypothetical and future (but near-ish-term).  Right now, this eliminates repetition in `caravel` of all the option names here and couples them more closely in case of future changes (i.e., I think the names should continue to match in both places). Bundling  the options by program allows us to minimize the import complexity required between the packages (taking each program as a unit, and just importing wherever desired the full bundle of programs `looper` offers. I could see naming each program's parser individually to allow a-la-carte import and use, but doing the same for the individual options that a program exposes feels strange, not particularly useful, and error-prone, though, so it feels preferable for each program to represent the specification as a single `Subparser` (or whatever name) instance. That's the definite, immediate benefit.

The less certain (but potential) and less immediate benefit _is_ as a foundation toward upcoming handling the actual schema / value types

**Comment by nsheff** [comment]
Looking at it some more I think this is really nice. I'm totally on board with the bundling for imports concept. A few thoughts:

- could the `name` and `opt` attributes be passed via `kwargs` ? Why name some of the fields, but not others? I think you have a reason for this but I'm not quite seeing it.
- related to my comment above: will we need to define any other classes for any other ArgumentParser capabilities (like mutually exclusive groups) ? I am wondering if there's any way we can make use of these capabilities without requiring too much retooling. Or, put another way, make the interface *as much like ArgumentParser as possible*, so we don't have to define things for each argumentparser method...

So, I guess the last thought is:

Are you sure it's not possible to just get all the information we need from the actual ArgumentParser object itself? If we *could* do it that way, I think it would be really simple. In other words, create the ArgumentParser object in looper. Then import that into caravel and inspect it to get whatever we need.

I have no idea if you *can* get everything you need from that, but if you can, it would save us from having to do this at all, wouldn't it?

Could we somehow take what you've done and actually wrap it into a new type of object that *extends* ArgumentParser?

**Comment by nsheff** [comment]
> Could we somehow take what you've done and actually wrap it into a new type of object that extends ArgumentParser?

Just to build on that... for example, in this new, `SuperArgumentParser` object, what if you, for example, override `add_argument` to do what you need to do, the functionality currently in the `CliOpt` object, and then just call the base `add_argument` function right there with the same args?

**Comment by vreuter** [comment]
[This](https://github.com/databio/caravel/pull/18/commits/ea4c464e83c926bae202cafd2dcfb3e134a2fb1b) accomplishes for now what I'm after here, and isolates the changes to `caravel`

**Pull request closed without merging**
