### PR TITLE
Jinja

### PR DESCRIPTION
**Pull request by nsheff**
Waiting on: 
- [ ] logmuse to pypi: https://github.com/databio/logmuse/issues/1

### CODE REVIEW

**Comment by michalstolarczyk** [comment]
I might need to make some changes related to the introduction of `logmuse` to `looper`. `looper` logging is not working in `caravel` now

**Comment by nsheff** [comment]
is this ready to be merged? did we solve the logging issues?

**Comment by vreuter** [comment]
Yeah I think we're go for merge :rocket: . @michalstolarczyk is there anything else we need to do first?

**Comment by michalstolarczyk** [comment]
No, let's merge

**Comment by nsheff** [comment]
ok go for it

**Pull request merged**
