### PR TITLE
v0.12.6

### PR DESCRIPTION
**Pull request by stolarczyk**
@jpsmith5 this is the PR for the closest release, which includes the summarizer tweaks requested in #220 but excludes the pipeline interface changes.

So use the `summarizer-updates` branch from now on

---
to do: 
- [x] release date

### CODE REVIEW

**Comment by nsheff** [comment]
@stolarczyk go ahead and release (after updating the date)

**Comment by nsheff** [comment]
actually I take it abck, I'm getting this error:

```
Traceback (most recent call last):
  File "/home/ns5bc/.local/bin/looper", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/ns5bc/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'eido>=0.0.4' distribution was not found and is required by loopercli
```

might want to postpone this until the peppy/eido issues are resolved.

**Comment by stolarczyk** [comment]
hmm, are you sure you're testing this branch, note it's not `dev`? There's no `eido` requirement

**Comment by nsheff** [comment]
> hmm, are you sure you're testing this branch, note it's not dev? There's no eido requirement

oops.

**Comment by nsheff** [comment]
ok, this is working for me.

**Pull request merged**
