### PR TITLE
0.12.2

### PR DESCRIPTION
**Pull request by nsheff**
Since we currently lack a functioning release version of looper, we need to make a new release to fix all the bugs (in looper and peppy).

Wait for: https://github.com/pepkit/peppy/pull/314

Milestone issues: https://github.com/pepkit/looper/milestone/5

### CODE REVIEW

**Comment by vreuter** [comment]
Tests pass for me locally (the peppy dev req that Travis can't get), and the pro-seq test case from @jpsmith5 seems to work, so this seems about ready. Are there other things either @michalstolarczyk or @nsheff want to first test?

**Comment by nsheff** [comment]
this is pretty basic, I think we will just need to wait for peppy 0.22 and then go for it.

**Comment by nsheff** [comment]
is this good to go just waiting on peppy?

**Comment by vreuter** [comment]
Yeah

**Pull request merged**
