### PR TITLE
Ensure protocol mapping key consistency

### LINKED ISSUE #21: protocol mappings broken
Looper version 0.8 has a problem; with the RNA-seq pipeline, for example, it gives the error of `No mapping for protocol: 'rnaKallisto'` even when there *is* a mapping for such a protocol.

I think something to do with implementing the catch-all asterisk may have broken the mapping code, or something. For a reprex look at the rnapipe pipeline.

reported by @aaron-gu

### PR DESCRIPTION
**Pull request by vreuter**
Fix #21

### CODE REVIEW

**Comment by vreuter** [comment]
This is into `master`since it's a bugfix. If this is merged, should we proceed with a `CHANGELOG` update and release a `v0.8.1`?

**Comment by nsheff** [comment]
@aaron-gu can you confirm that this solves the problem you were having with rnapipe on the latest looper version?

**Comment by nsheff** [comment]
This did solve the problem for me.

**Comment by nsheff** [comment]
> This is into master since it's a bugfix. If this is merged, should we proceed with a CHANGELOG update and release a v0.8.1?

That sounds good to me.

**Comment by nsheff** [comment]
This is into master since it's a bugfix. If this is merged, should we proceed with a CHANGELOG update and release a v0.8.1?

That sounds good to me.

Actually let's put this together with #20 (which is also a bug fix) so lets' put it into dev and then into master from there for 1 point release with both bugfixes.

**Pull request merged**
