### PR TITLE
1.2.1

### LINKED ISSUE #268: relative pipeline interface paths should be relative to the PEP
Right now, if you use a relative pipeline interface path, such as is used in the [hello_looper repository](https://github.com/pepkit/hello_looper), looper is assuming the piface will be relative to the current working directory, which is wrong. it should be considered relative to the PEP that specifies the piface.

### LINKED ISSUE #286: Unclear error message with PEP without looper section
If running `looper run` with a PEP without a `looper` section, looper throws an error that is hard to understand:
```
Traceback (most recent call last):
  File "//home/afr/.local/bin/looper", line 8, in <module>
    sys.exit(main())
  File "/home/afr/.local/lib/python3.8/site-packages/looper/looper.py", line 691, in main
    args = enrich_args_via_cfg(args, aux_parser)
  File "/home/afr/.local/lib/python3.8/site-packages/looper/utils.py", line 213, in enrich_args_via_cfg
    elif dest in cfg_args_all:
TypeError: argument of type 'NoneType' is not iterable
```

If a `looper` section is really required in the PEP, then a message stating that is absent should be presented.

### PR DESCRIPTION
**Pull request by nsheff**
- bugfix on relative project piface paths.
- fix #268 
- fix #286

todo: 
- [x]  release date

### CODE REVIEW

**Comment by nsheff** [comment]
should we wrap up this bugfix release?

**Comment by stolarczyk** [comment]
it think it's ready @nsheff

**Comment by nsheff** [comment]
I guess we should release this before I go too much further down the CWL features train, eh?

**Comment by stolarczyk** [comment]
ok, let's do it

**Pull request merged**
