### PR TITLE
remove python 3.4

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by nsheff** [comment]
why remove python 3.4? just curious...

**Comment by vreuter** [comment]
I noticed a couple packages that I use a lot have dropped it, I think due to some vulnerabilities or other weaknesses that are (perceived as, at least) sufficient to warrant moving on. I think some of the scientific stack is dropping it, at least maybe pandas, numpy, xarray, and scikit-learn.

**Comment by vreuter** [comment]
We’ll need to drop 2.7 at some point since I think it’s sunsetting in 2020 for pip, but it feels like that’s a bigger change that we can wait on?

**Comment by nsheff** [comment]
yep. so over the course of the next year, we sunset 2.7. I guess I need to embrace python 3 for real.

https://python3statement.org/

**Pull request merged**
