### PR TITLE
#149

### PR DESCRIPTION
**Pull request by vreuter**

### CODE REVIEW

**Comment by nsheff** [comment]
This type of change will essentially move the HTML defaults from looper to caravel. Are you sure we should do it this way? While I applaud the goal to keep all the caravel stuff in caravel and not in looper... what will you do with the range-based ones that have specific ranges?

**Comment by nsheff** [comment]
Two things I don't really like about this approach:

1.  the default for this option (`False`) is now in 2 places, one in the looper argparser, one here. In the other way, it's true that it's duplicated, but at lease they're right next to each other... is there a way to actually get this information from the argument itself so it's not duplicated?

2. This requires hard coding the options into caravel. I really want to avoid that... if the looper API changes, I want caravel to update automatically.

**Comment by nsheff** [comment]
I guess the advantage of the duplication is that caravel and looper could have different defaults...

I think I favor automation and single-source code over that, though.

**Comment by vreuter** [comment]
> Can we think of a way to solve these issues while retaining the separation (which I do like).

The "old way" lacks separation in one sense (`looper` uses knowledge of `caravel` internals), has it in another (no option names in `caravel`). It makes no sense to have bidirectional knowledge requirements (what _is_ a "dependency" then?)

I'd prefer not to debate this and just implement whatever's desired; it seems quite likely that consensus on this will not arrive.

**Comment by michalstolarczyk** [comment]
> if the looper API changes, I want caravel to update automatically. To add: in the old way, this was accomplished

exactly. This was the _main premise_  and advantage of the current approach.

**Comment by vreuter** [comment]
https://github.com/pepkit/looper/commit/8ad81ab3adea263de8b117d7c432a057c727c72c

**Pull request closed without merging**
