### PR TITLE
Release 0.11.1

### PR DESCRIPTION
**Pull request by nsheff**
Official release for my master pushes, update divvy imports and docs.

### CODE REVIEW

**Comment by nsheff** [comment]
@vreuter This is ready to go as soon as you're ready. after releasing `divvy` to make sure we pass tests.

**Comment by nsheff** [comment]
@vreuter actually give me a few more minutes for one last documentation change on this one, I'm almost done... let me know when you're ready

**Comment by nsheff** [comment]
Ok I'm good to go -- I just was making changes to the mkdocs theme.

**Comment by vreuter** [comment]
OK I got the `divvy` logo working on test PyPI so am just waiting for the latest build to pass then will upload that and proceed with this.

**Comment by nsheff** [comment]
cool!

this build still failed... do we need to add divvy to the requirements-test file ?

**Comment by nsheff** [comment]
nevermind... I was looking at the peppy build: 

https://travis-ci.org/pepkit/peppy

I think we need to make that change there

**Comment by vreuter** [comment]
Well, the `peppy` one at least also depends on a newer  `attmap`, but it's just the `dev` build at least. I'm going to look at what the `attmap` diff is and consider a 0.6.1 or 0.7 today. I think we're set on this one on latest build (465)

**Pull request merged**
