### PR TITLE
Hotfix failed flag  -- release 1.3.1

### LINKED ISSUE #303: strange flag error message
```
looper run examples/test_config.yaml --limit 1
Looper version: 1.2.1
Command: run
## [1 of 4] sample: RRBS_human; pipeline: RRBS
> Skipping sample because no failed flag found. Flags found: ['/home/ns5bc/dnameth/results_pipeline/RRBS_human/RRBS_failed.flag'
```

shouldn't that say "failed flag found" ?

### PR DESCRIPTION
**Pull request by nsheff**
Fix #303

### CODE REVIEW

**Comment by nsheff** [comment]
This has cost me so much time with multiple complaints from users that I need to just get a fix out there to solve this. Should have done this 6 months ago.

**Comment by nsheff** [comment]
Just want to make sure this is OK with you @stolarczyk. Hopefully the next 1.4.0 release is not too far behind.

**Comment by nsheff** [comment]
@stolarczyk can I release this?

**Review by stolarczyk — APPROVED** [review]
Sure. Sorry for the delay

**Pull request merged**
